language: python
python: "3.5"
sudo: false
cache: pip
env:
  - TOXENV=py27-django203
  - TOXENV=py33-django203
  - TOXENV=py34-django203
  - TOXENV=py35-django203
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
